### ISSUE TITLE
Provide play-services-free build flavour

### ISSUE THREAD

**Issue by ghost** [beegee-tokyo/phoenix#2]
Google's play-services is a non-free dependency, so FDroid -- a free/libre/open-source app repository -- can no longer builds this app. It would be great if could remove them or provide special gradle build flavour without them.

**Comment by beegee-tokyo** [comment]
Please teach me how to do set up gradle (and the source code) to have a special flavour for FDroid.

**Comment by ghost** [comment]
See https://sites.google.com/a/android.com/tools/tech-docs/new-build-system/user-guide#TOC-Product-flavors, basically you add

```
android {
    productFlavors {
        fdroid {}
        play {}
    }
}
```

Flavour-specific code is in src/FLAVOUR instead of src/main, dependencies can be specified to only be relevant for a specific flavour by using `flavourCompile` intead of `compile` on the dependency list, e.g.

```
playCompile 'com.google.android.gms:play-services:7.0.0'
```

Everything else should be available in the gradle user manual or in tutorials out there.

**Comment by beegee-tokyo** [comment]
Number of installations is too small for this additional effort.
