### ISSUE TITLE
ITALIAN LANGUAGE, PLEASE!

### ISSUE THREAD

**Issue by ghost** [beegee-tokyo/phoenix#3]

**Comment by beegee-tokyo** [comment]
I do not speak Italian. But if you give me translations of all texts stored in [strings.xml](https://github.com/beegee-tokyo/phoenix/blob/master/app/src/main/res/values/strings.xml) in Italian, I can add that language.

**Comment by ghost** [comment]
Sorry for the retard. In any case, for the translation, no problem; But you feel that it may take some time
