### ISSUE TITLE
Turn-off option

### ISSUE THREAD

**Issue by ghost** [beegee-tokyo/phoenix#4]
Hi! Please, add an ability to turn-off the phone with the same features/options to Reboot ability!

**Comment by beegee-tokyo** [comment]
Android OS does not allow an application to shutdown/turn-off a device.

**Comment by ghost** [comment]
Wait, there is "DEVICE_POWER" permission, that allows you to turn on or off the phone. 

Also, on Play Store, there are apps that allow you to do it, even remotely!
