### ISSUE TITLE
F-Droid version 

### ISSUE THREAD

**Issue by ghost** [beegee-tokyo/phoenix#5]
The version is stop to 3.0; is possible load the last version (4.0) on F-Droid?

**Comment by beegee-tokyo** [comment]
Version 4 is identical from functionality, but contains Google advertisments. Cannot upload to F-Droid.

**Comment by ghost** [comment]
I understand. However, the development of free version continue separately from that of the Play Store, or version 3.0 is the last version?

**Comment by beegee-tokyo** [comment]
No more development on this project.
